### PR TITLE
Bug fix: Mod Dependencies being entered into multiple Req/Opt/Forb lists.

### PR DESCRIPTION
**Pull request by Smithor**
A fix for a bug where a mod's dependencies are extracted alongside the actual package ID. Now only the package ID attached to the parent node specified is returned. This could cause problems like, a mod being in both the required and optional lists (mod in required, re-texture in optional), which in my experience causes the user to not be able to join the world.

Also fixed a bug where a mod could be in two or more lists at the same time, which potentially caused an inability for a player to connect to the server. Now, Required takes precedence over Optional and Forbidden, and Optional wins over Forbidden.

XmlParser.cs - new function
ModManger.cs now uses new function

I am not 100% certain that this solution works as is, but I would like it reviewed. I haven't got the build script working on my end because I already stayed up too late, but even if this is not the solution, it is a simple problem to solve.

### CODE REVIEW

**Comment by Smithor** [comment]
Thank you for checking it out, it's what I get for rushing it out while tired. 

I can fix it properly in a couple days when I'm free again, but the problem itself is very simple, the parse function doesn't care if the packageID element is inside the ModDependencies or not, when it really should for the purposes of collecting the actual packageId of the mod. There are multiple ways to solve the problem, but the easiest for this project is just to grab only the element that is a child of the modmetadata element. Will have no problems, and probably doesn't even need the data confirmation that was added in ModManager.

If no one else has got to it by the weekend then I'll fix it then. I just thought I'd whip up the answer real quick instead of writing a bug report, but that's my bad for not finishing the build environment first.

**Comment by Smithor** [comment]
Alright, commit actually tested this time, and it seems to work good. Nothing changed other than those bits and the xml file. I would appreciate a second look.

**Comment by Byte-Nova** [comment]
Made some changes to the mod list system to make it so it doesn't send duplicate mods to the client, some testing would be appreciated.

**Comment by Smithor** [comment]
Live-Tested with a full set of mods, no duplication or missing values. I read through ModManager fully and saw no logic problems. I think solution is complete.

Once again my apologies for not testing at the first, especially for such a simple fix.

**Review by Byte-Nova — APPROVED** [review]

**Pull request merged**
